### ISSUE TITLE
Will the spreadsheet be updated?

### ISSUE THREAD

**Issue by samdutton** [chromium/blink-intent-tracker#13]
I noticed that the most recent update in the spreadsheet is from 2021. Is there a plan to continue updating the spreadsheet?

**Comment by yoavweiss** [comment]
I don't believe there are. Intent reviews have moved over to chromestatus.com.
What's your use case?

**Comment by samdutton** [comment]
> What's your use case?

'View all intents'
'View all intents relating to API X'
'View all intents to prototype/experiment/ship/deprecate'
'View all intents for the following dates: ...'
...

In other words, anything you can do with data in a spreadsheet.

**Comment by yoavweiss** [comment]
https://docs.google.com/spreadsheets/d/1pvXEMD5pRioognaqEzglS-4ZBSQ_YmzL8Fiz7yt4Bb4/edit#gid=0&fvid=1112765777 seems to be still working (despite the fact I haven't maintained the scripts in a while)

**Comment by samdutton** [comment]
Ah — that's good. I think it hadn't updated when I looked, but seems OK now. Thanks @yoavweiss !
